version: "3"

services:
  db:
    image: mysql:8.0.19
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  server:
    build: ./server
    volumes:
      - ./server:/app/server/
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  client:
    build: ./client
    restart: always
    tty: true
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn dev
    depends_on:
      - server

volumes:
  mysql: